# File: alembic/versions/327ef7732e77.py (HANYA UNTUK MENAMBAH KOLOM KE USERS)

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Diperlukan untuk tipe data tertentu

# revision identifiers, used by Alembic.
revision: str = '327ef7732e77'
down_revision: Union[str, Sequence[str], None] = 'dc41af278e4a' # ID revisi sebelumnya
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Menambahkan kolom reset_expires_at ke tabel users."""
    # ### commands auto generated by Alembic - TELAH DIHAPUS DAN DIGANTI ###
    
    # PERINTAH HANYA UNTUK MENAMBAH KOLOM reset_expires_at
    op.add_column(
        'users',
        sa.Column('reset_expires_at', sa.DateTime(timezone=True), nullable=True)
    )
    # Catatan: Kolom reset_token (jika hilang) juga perlu ditambahkan, 
    # namun diasumsikan dc41af278e4a sudah menambahkan reset_token.
    # Jika Anda ingin lebih aman, tambahkan juga:
    # op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=True)) 
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Menghapus kolom reset_expires_at."""
    # ### commands auto generated by Alembic - TELAH DIHAPUS DAN DIGANTI ###

    # PERINTAH HANYA UNTUK MENGHAPUS KOLOM reset_expires_at
    op.drop_column('users', 'reset_expires_at')
    
    # ### end Alembic commands ###