"""Add missing reset password columns

Revision ID: dc50f4368984
Revises: 327ef7732e77
Create Date: 2025-12-11 18:35:28.870770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc50f4368984'
down_revision: Union[str, Sequence[str], None] = '327ef7732e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_course_enroll_id_enroll'), table_name='course_enroll')
    op.drop_table('course_enroll')
    op.drop_index(op.f('ix_grading_id_grade'), table_name='grading')
    op.drop_table('grading')
    op.drop_index(op.f('ix_course_id_course'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_submissions_id_submission'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_assignments_id_assignment'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id_assignment', sa.INTEGER(), server_default=sa.text("nextval('assignments_id_assignment_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_course', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('judul', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('soal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kunci_jawaban', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['course.id_course'], name='assignments_id_course_fkey'),
    sa.PrimaryKeyConstraint('id_assignment', name='assignments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_assignments_id_assignment'), 'assignments', ['id_assignment'], unique=False)
    op.create_table('submissions',
    sa.Column('id_submission', sa.INTEGER(), server_default=sa.text("nextval('submissions_id_submission_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_assignment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_mahasiswa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jawaban', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_assignment'], ['assignments.id_assignment'], name='submissions_id_assignment_fkey'),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['users.id_user'], name='submissions_id_mahasiswa_fkey'),
    sa.PrimaryKeyConstraint('id_submission', name='submissions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_submissions_id_submission'), 'submissions', ['id_submission'], unique=False)
    op.create_table('course',
    sa.Column('id_course', sa.INTEGER(), server_default=sa.text("nextval('course_id_course_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('kode_course', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nama_course', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id_dosen', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_dosen'], ['users.id_user'], name='course_id_dosen_fkey'),
    sa.PrimaryKeyConstraint('id_course', name='course_pkey'),
    sa.UniqueConstraint('kode_course', name='course_kode_course_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_course_id_course'), 'course', ['id_course'], unique=False)
    op.create_table('grading',
    sa.Column('id_grade', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_submission', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skor_ai', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('skor_dosen', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('feedback_ai', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feedback_dosen', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_submission'], ['submissions.id_submission'], name=op.f('grading_id_submission_fkey')),
    sa.PrimaryKeyConstraint('id_grade', name=op.f('grading_pkey'))
    )
    op.create_index(op.f('ix_grading_id_grade'), 'grading', ['id_grade'], unique=False)
    op.create_table('course_enroll',
    sa.Column('id_enroll', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_course', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_mahasiswa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enroll_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['course.id_course'], name=op.f('course_enroll_id_course_fkey')),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['users.id_user'], name=op.f('course_enroll_id_mahasiswa_fkey')),
    sa.PrimaryKeyConstraint('id_enroll', name=op.f('course_enroll_pkey'))
    )
    op.create_index(op.f('ix_course_enroll_id_enroll'), 'course_enroll', ['id_enroll'], unique=False)
    op.create_table('users',
    sa.Column('id_user', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nim_nip', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'dosen', 'mahasiswa', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('prodi', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_user', name=op.f('users_pkey')),
    sa.UniqueConstraint('nim_nip', name=op.f('users_nim_nip_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    # ### end Alembic commands ###
